In [7]:
print("Macierz A1:")
A1 = matrix([[2.40827208, -0.36066254, 0.80575445, 0.46309511, 1.20708553], [-0.36066254, 1.14839502, 0.02576113, 0.02672584, -1.03949556], [0.80575445 , 0.02576113, 2.45964907 , 0.13824088, 0.0472749], [0.46309511 , 0.02672584, 0.13824088, 2.05614464, -0.9434493], [1.20708553, -1.03949556, 0.0472749, -0.9434493, 1.92753926]])
print(A1)
print("----------------------------------------------------------------------------------------------------")
print("Macierz A2")
print("----------------------------------------------------------------------------------------------------")
A2 = matrix([[2.61370745, -0.6334453, 0.76061329, 0.24938964, 0.82783473], [-0.6334453, 1.51060349, 0.08570081, 0.31048984, -0.53591589], [0.76061329, 0.08570081, 2.46956812, 0.18519926, 0.13060923], [0.24938964, 0.31048984, 0.18519926, 2.27845311, -0.54893124], [0.82783473, -0.53591589, 0.13060923, -0.54893124, 2.6276678]])
print(A2)
print("----------------------------------------------------------------------------------------------------")
print("Wektor b:")
print("----------------------------------------------------------------------------------------------------")
b = vector([5.40780228, 3.67008677, 3.12306266, -1.11187948, 0.54437218])
print(b)
print("----------------------------------------------------------------------------------------------------")
print("Wektor bprim:")
print("----------------------------------------------------------------------------------------------------")
bprim = vector([0.00001, 0, 0, 0, 0]) + b
print(bprim)
print("----------------------------------------------------------------------------------------------------")
print("Rozwiazanie y1:")
print("----------------------------------------------------------------------------------------------------")
y1 = A1.solve_right(b)
print(y1)
print("----------------------------------------------------------------------------------------------------")
print("Rozwiazanie y1prim:")
print("----------------------------------------------------------------------------------------------------")
y1prim = A1.solve_right(bprim)
print(y1prim)
print("----------------------------------------------------------------------------------------------------")
print("Delta1:")
print("----------------------------------------------------------------------------------------------------")
Delta1 = (y1-y1prim).norm(2)
print(Delta1)
print("----------------------------------------------------------------------------------------------------")
print("Rozwiazanie y2:")
print("----------------------------------------------------------------------------------------------------")
y2 = A2.solve_right(b)
print(y2)
print("----------------------------------------------------------------------------------------------------")
print("Rozwiazanie y2prim:")
print("----------------------------------------------------------------------------------------------------")
y2prim = A2.solve_right(bprim)
print(y2prim)
print("----------------------------------------------------------------------------------------------------")
print("Delta2:")
print("----------------------------------------------------------------------------------------------------")
Delta2 = (y2-y2prim).norm(2)
print(Delta2)
print("----------------------------------------------------------------------------------------------------")
print("Delta1 - Delta2:")
print("----------------------------------------------------------------------------------------------------")
Roznica = Delta1-Delta2
print(Roznica)
print("----------------------------------------------------------------------------------------------------")
import numpy
eig1 = numpy.linalg.eigvals(A1)
print("Kappa1:")
k1 = (max(eig1)/min(eig1))
print(k1)
print("----------------------------------------------------------------------------------------------------")
eig2 = numpy.linalg.eigvals(A2)
print("Kappa2:")
k2 = (max(eig2)/min(eig2))
print(k2)

Macierz A1:
[  2.40827208000000 -0.360662540000000  0.805754450000000  0.463095110000000   1.20708553000000]
[-0.360662540000000   1.14839502000000 0.0257611300000000 0.0267258400000000  -1.03949556000000]
[ 0.805754450000000 0.0257611300000000   2.45964907000000  0.138240880000000 0.0472749000000000]
[ 0.463095110000000 0.0267258400000000  0.138240880000000   2.05614464000000 -0.943449300000000]
[  1.20708553000000  -1.03949556000000 0.0472749000000000 -0.943449300000000   1.92753926000000]
----------------------------------------------------------------------------------------------------
Macierz A2
----------------------------------------------------------------------------------------------------
[  2.61370745000000 -0.633445300000000  0.760613290000000  0.249389640000000  0.827834730000000]
[-0.633445300000000   1.51060349000000 0.0857008100000000  0.310489840000000 -0.535915890000000]
[ 0.760613290000000 0.0857008100000000   2.46956812000000  0.185199260000000  0.130609230000000]